service: KGSE #Name of your App
# package:
#   exclude:
#     - node_modules/**

plugins:
  - serverless-offline
provider:
 name: aws
 runtime: nodejs12.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: production
 region: us-west-2 # AWS region

functions:
  api:
   handler: lambda.handler
   events:
    - http: ANY {proxy+}
    - http: ANY /